---
- name: Bootstrap base box
  user: root
  hosts: application
  roles:
    - f-s-v.railsbox-image
- name: Install rails box for markin application
  hosts: application
  user: "{{ railsbox_user }}"
  roles:
    - role: f-s-v.postgresql-database
      psql_db_name: markin_production
      psql_version: 9.3
      psql_owner: "{{ railsbox_user }}"
    - f-s-v.railsbox-bower-runtime
    - f-s-v.railsbox-rails-application
    - f-s-v.railsbox-foreman-services
    - f-s-v.railsbox-nginx-upstream-rails-application
